drop database redeSocial
go
create database redeSocial
go
use redeSocial
go
CREATE TABLE USERTABLE
(
    CPF VARCHAR(11) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
    SALT VARCHAR (120),
    PASSWORD VARCHAR(120) NOT NULL,
    BORNDATE DATE,
    ASSIGNDATE DATE NOT NULL DEFAULT GETDATE(),
)

CREATE TABLE COMUNITY
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
)

CREATE TABLE RESPONSIBILITY
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
)

CREATE TABLE POSTS
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_COMUNITY INT FOREIGN KEY(ID_COMUNITY) REFERENCES COMUNITY(ID),
    ID_USER VARCHAR(11) FOREIGN KEY(ID_USER) REFERENCES USERTABLE(CPF),
    TITLE VARCHAR(60),
    POST_DATA VARCHAR(500),
    DATE_PUBLISH DATE,
)

CREATE TABLE LIKES 
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USER VARCHAR(11) FOREIGN KEY (ID_USER) REFERENCES USERTABLE(CPF),
    ID_POST INT FOREIGN KEY REFERENCES POSTS(ID)
)

CREATE TABLE COMMENTS
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USER VARCHAR(11) FOREIGN KEY (ID_USER) REFERENCES USERTABLE(CPF),
    ID_POST INT FOREIGN KEY (ID_POST) REFERENCES POSTS(ID),
    COMMENT_DATA VARCHAR(300)
)

CREATE TABLE HAS_RESPONSIBILITY
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_COMUNITY INT FOREIGN KEY(ID_COMUNITY) REFERENCES COMUNITY(ID),
    ID_USER VARCHAR(11) FOREIGN KEY(ID_USER) REFERENCES USERTABLE(CPF),
    ID_RESPONSIBILITY INT FOREIGN KEY(ID_RESPONSIBILITY) REFERENCES RESPONSIBILITY(ID),
)

CREATE TABLE PERMISSION
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPTION VARCHAR(100) NOT NULL,
)

CREATE TABLE RESPONSIBILITY_PERMISSION
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_RESPONSIBILITY INT FOREIGN KEY(ID_RESPONSIBILITY) REFERENCES RESPONSIBILITY(ID),
    ID_PERMISSION INT FOREIGN KEY(ID_PERMISSION) REFERENCES PERMISSION(ID)
)

SELECT * FROM USERTABLE