CREATE TABLE USERTABLE
(
    CPF VARCHAR(11) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    BORNDATE DATE,
    ASSIGNDATE DATE NOT NULL DEFAULT GETDATE(),
    SALT VARCHAR (12),
    PASSWORD VARCHAR(36) NOT NULL,
)

CREATE TABLE COMUNITY
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_OWNER INT FOREING KEY(ID_OWNER) REFERENCES USERTABLE(CPF)
    ID_RESPONSIBILITY INT FOREING KEY(ID_RESPONSIBILITY) REFERENCES 

)

CREATE TABLE POSTS
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_COMUNITY INT FOREING KEY(ID_COMUNITY) REFERENCES COMUNITY(ID)
    ID_USER INT FOREING KEY(ID_USER) REFERENCES USERTABLE(CPF)
    TITLE VARCHAR(60)
    POST_DATA VARCHAR(213)
    DATE_PUBLISH DATE
    
)